### ISSUE TITLE
🚂 Frontend framework 🚂

### ISSUE THREAD

**Issue by GlynnPhillips** [dpvitt/mindful#4]
My line manager was showing me this yesterday and I thought it might be nice to give a go for the frontend [🚂 Choo 🚂](https://github.com/yoshuawuyts/choo)

I like the following about it (for a small project like this)

- Lightweight
- No crazy list of dev requirements / build steps
- Isomorphic
- Nice simple use of template strings (no jsx etc)
- Chance to try something new

**Comment by dpvitt** [comment]
For something as simple as this I think it would be perfect. +1 simple, light and isomorphic. I'm going to bloody close this as it looks gr8 m8, good find.
